sudo: false
language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash)
